### ISSUE TITLE
Upload von gezipptem xtf nicht möglich?

### ISSUE THREAD

**Issue by sjib** [sogis/ilivalidatorws#18]
War dies nur ein ein einmalige Fehlermeldung beim Upload einer gezippten xtf Datei oder wird das generell nicht unterstützt? Auch ein zweiter Versuch 5 minuten später ergab das gleiche Resultat.
```

Unbekannter Server Fehler

Ein unbekannter Server Fehler ist aufgetreten. Bitte versuchen Sie es in ein paar Minuten noch mal.

Sollte die Fehlermeldung danach immer noch erscheinen, beschreiben Sie bitte in einem E-Mail bei welcher Dienstleistung und welchem Arbeitsschritt der Fehler auftrat. Bitte fügen Sie zusätzlich im E-Mail untenstehenden Fehlerinformationen hinzu und senden dies an servicedesk@aio.so.ch.

Fehlerinformationen:
URL: https://geo.so.ch
Path: /ilivalidator/api/jobs
Client IP address: 127.0.0.1
Server IP address: 127.0.0.1
Date and time: Saturday, 12-Oct-2024 18:59:37 CEST
Request correlator: 7f0100-2466-2024.10.12_1659.35.501-001 
```

Ich wollte ein xtf von > 100 mb lieber als zip hochladen.

**Comment by edigonzales** [comment]
Wird bewusst nicht unterstützt. Ich wollte mich nicht um das Zip-Handling kümmern: Gezipptes XTF mit/ohne (Sub-)Verzeichnisstruktur etc.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Stefan ***@***.***>
Sent: Saturday, October 12, 2024 7:21:21 PM
To: sogis/ilivalidatorws ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sogis/ilivalidatorws] Upload von gezipptem xtf nicht möglich? (Issue #18)


War dies nur ein ein einmalige Fehlermeldung beim Upload einer gezippten xtf Datei oder wird das generell nicht unterstützt? Auch ein zweiter Versuch 5 minuten später ergab das gleiche Resultat.


Unbekannter Server Fehler

Ein unbekannter Server Fehler ist aufgetreten. Bitte versuchen Sie es in ein paar Minuten noch mal.

Sollte die Fehlermeldung danach immer noch erscheinen, beschreiben Sie bitte in einem E-Mail bei welcher Dienstleistung und welchem Arbeitsschritt der Fehler auftrat. Bitte fügen Sie zusätzlich im E-Mail untenstehenden Fehlerinformationen hinzu und senden dies an ***@***.***

Fehlerinformationen:
URL: https://geo.so.ch
Path: /ilivalidator/api/jobs
Client IP address: 127.0.0.1
Server IP address: 127.0.0.1
Date and time: Saturday, 12-Oct-2024 18:59:37 CEST
Request correlator: 7f0100-2466-2024.10.12_1659.35.501-001


Ich wollte ein xtf von > 100 mb lieber als zip hochladen.

**Comment by edigonzales** [comment]
@sjib Sollte nun funktionieren: https://geo.so.ch/ilivalidator/
