### ISSUE TITLE
Der dokumentierte Default-Wert stimmt nicht

### ISSUE THREAD

**Issue by schmandr** [sogis/ilivalidatorws#7]
https://github.com/sogis/ilivalidatorws/blob/cc1d977471ffa4b0dbc66200ca2244dc4ab84e8a/README.md?plain=1#L83
Der Default-Wert ist m.E. `/work/`, nicht `/tmp/`, wie es in der Doku steht.

https://github.com/sogis/ilivalidatorws/blob/cc1d977471ffa4b0dbc66200ca2244dc4ab84e8a/README.md?plain=1#L87
Und ich vermute, dass der hier dokumentierte Default-Wert ebenfalls nicht stimmt, sondern mir scheint, dass die DB unter `/work/` angelegt wird.

Und wenn ich mich nicht irre, wird die DB immer unter `/work/` angelegt, auch wenn man `WORK_DIRECTORY` auf sonst was setzt. Das müsste nicht so sein, oder?

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/ilivalidatorws/commit/99e93334100d47eb36e77c11cbc95907aacc4323

Es stimmt irgendwie beides. Das Docker-Image verwendet automatisch und bewusst eicht andere Werte als das Jar.
